### ISSUE TITLE
Failure of installation

### ISSUE THREAD

**Issue by Riverboat8865** [themeliolabs/melwallet-client#11]
When I tried to compile ` cargo install --locked melwallet-client`, I got the following error:
```
Compiling dashmap v5.4.0
error: Unrecognized option: 'diagnostic-width'

error: could not compile `dashmap` (lib)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `melwallet-client v0.7.3`, intermediate artifacts can be found at `/tmp/cargo-installjUveoW`
```
My rust and cargo versions are 1.70.0. Is this a dashmap problem or my system's problem?

**Comment by ghost** [comment]
What is your system environment?

**Comment by Riverboat8865** [comment]
It is 20.04.1 Ubuntu with Intel  i7-7500U CPU

**Comment by ghost** [comment]
This issue seems to have been solved in the Discord community, please close the issue, thanks!

**Comment by Alizter** [comment]
What was the solution?
