### ISSUE TITLE
Password is always incorrect

### ISSUE THREAD

**Issue by ghost** [themeliolabs/melwallet-client#5]
As the picture shows:

![image](https://user-images.githubusercontent.com/95868829/171845173-4e745186-7ea3-431e-a17b-24eee1ce4671.png)

Environment info:

- OS: Windows 11 Pro Workstation 10.0.22000 Build 22000
- CPU: Ryzen 7 3700X
- RAM: 32 GiB 3533 MHz DDR4

**Comment by nullchinchilla** [comment]
This is fixed in 0.6.6. It was a line-terminator handling issue (`\r` vs `\r\n`)
