### ISSUE TITLE
Duplicate MEL amounts

### ISSUE THREAD

**Issue by ghost** [themeliolabs/melwallet-client#8]
## Details

As shown in the figure (the part boxed out in red):

![image](https://user-images.githubusercontent.com/95868829/222944131-7bc34504-4062-42bb-a61c-d7f3a9150cb6.png)

## Environment Information

- melawlletd version: 0.6.2
- melwallet-cli version: 0.7.2

**Comment by sadministrator** [comment]
The top MEL amount is supposed to be just the total MEL balance, the one underneath is part of the detailed balance. Labels have been added to clear this up.
