### ISSUE TITLE
Incorrect description

### ISSUE THREAD

**Issue by ghost** [themeliolabs/melwallet-client#9]
## Details

Sometimes it is indeed a error, such as this time:

![image](https://user-images.githubusercontent.com/95868829/222965543-511d247f-790e-498e-850d-8f82037e2713.png)

But sometimes it's not an error, it's just a string of information that shouldn't be described as an Error:

![image](https://user-images.githubusercontent.com/95868829/222965588-ebe528c3-68ee-4e55-b75e-cf60eeafcf23.png)

## Environment Information

- melawlletd version: 0.6.2
- melwallet-cli version: 0.7.2

**Comment by sadministrator** [comment]
Fixed!
